"""initial schema

Revision ID: 357cc35ad234
Revises: 
Create Date: 2026-04-01 09:31:48.458635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '357cc35ad234'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('primary_contact', sa.String(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_findings',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description_technical', sa.Text(), nullable=False),
    sa.Column('description_executive', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severityenum'), nullable=False),
    sa.Column('cvss_score_default', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('remediation_steps', sa.Text(), nullable=False),
    sa.Column('remediation_steps_enabled', sa.Boolean(), nullable=False),
    sa.Column('vertical', sa.String(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('framework_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questionnaire_trigger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_ot_specific', sa.Boolean(), nullable=False),
    sa.Column('ref_cve_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_cwe_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_cisa_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_nist_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_nvd_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_manufacturer_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagements',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('pentest', 'gap_assessment', 'vulnerability_assessment', 'tabletop', 'tsa_directive', 'compliance_assessment', name='engagementtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('scoping', 'active', 'in_review', 'delivered', 'closed', name='engagementstatusenum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('scope_description', sa.Text(), nullable=True),
    sa.Column('engagement_lead', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_finding_references',
    sa.Column('library_finding_id', sa.UUID(), nullable=False),
    sa.Column('ref_type', sa.Enum('cve', 'cwe', 'cisa', 'nist', 'nvd', 'manufacturer', name='reftypeenum'), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_finding_id'], ['library_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('engagement_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('audience', sa.Enum('technical', 'executive', name='audienceenum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_review', 'final', name='reportstatusenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_sections',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.Enum('executive_summary', 'findings_summary', 'crown_jewel', 'critical_findings', 'high_findings', 'medium_findings', 'low_findings', 'informational', 'closing', 'appendix', name='sectiontypeenum'), nullable=False),
    sa.Column('severity_filter', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severityenum'), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('library_finding_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('description_technical', sa.Text(), nullable=False),
    sa.Column('description_executive', sa.Text(), nullable=False),
    sa.Column('severity_default', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severityenum'), nullable=False),
    sa.Column('severity_override', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severityenum'), nullable=True),
    sa.Column('severity_effective', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severityenum'), nullable=False),
    sa.Column('cvss_score_default', sa.Float(), nullable=True),
    sa.Column('cvss_score_override', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('remediation_steps', sa.Text(), nullable=False),
    sa.Column('remediation_steps_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_placement_override', sa.Boolean(), nullable=False),
    sa.Column('override_justification', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_ot_specific', sa.Boolean(), nullable=False),
    sa.Column('ref_cve_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_cwe_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_cisa_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_nist_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_nvd_enabled', sa.Boolean(), nullable=False),
    sa.Column('ref_manufacturer_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_finding_id'], ['library_findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['report_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'log', 'config', 'pcap', 'other', name='filetypeenum'), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('protection_adequacy', sa.Enum('adequate', 'partial', 'inadequate', 'unknown', name='protectionadequacyenum'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_references',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('ref_type', sa.Enum('cve', 'cwe', 'cisa', 'nist', 'nvd', 'manufacturer', name='reftypeenum'), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_references')
    op.drop_table('evidence')
    op.drop_table('findings')
    op.drop_table('report_sections')
    op.drop_table('reports')
    op.drop_table('library_finding_references')
    op.drop_table('engagements')
    op.drop_table('library_findings')
    op.drop_table('clients')
    # ### end Alembic commands ###
