"""add_username_firstname_lastname_to_user

Revision ID: 3aea562da73c
Revises: 52f028138a49
Create Date: 2026-04-02 08:29:37.454053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aea562da73c'
down_revision: Union[str, None] = '52f028138a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('users', sa.Column('first_name', sa.String(length=128), nullable=False, server_default=''))
    op.add_column('users', sa.Column('last_name', sa.String(length=128), nullable=False, server_default=''))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
