"""add_document_templates_table

Revision ID: b3dde244ed76
Revises: 1c5c4eb6c776
Create Date: 2026-04-07 15:21:32.346753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3dde244ed76'
down_revision: Union[str, None] = '1c5c4eb6c776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
